### ISSUE TITLE
Apparently no implementation to validate hashes

### ISSUE THREAD

**Issue by loganyoung** [ChrisMcKee/cryptsharp#6]
I find myself needing to reverse engineer this a little bit as I can't find a public function that allows me to validate an entered password against a known hash.

**Comment by ChrisMcKee** [comment]
Unless you have a specific need for the library as per https://www.zer7.com/software.php?page=cryptsharp
For hashing passwords, I'd recommend bcrypt & https://github.com/BcryptNet/bcrypt.net which is maintained and has been checked.
